# Generated by Django 4.2.1 on 2023-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='timezone_str',
            field=models.CharField(default='America/Chicago', max_length=200),
        ),
    ]
